"""add_branding_and_agencies

Revision ID: db9f1d5b40e2
Revises: 176390fceeb1
Create Date: 2025-12-18 17:37:51.818092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9f1d5b40e2'
down_revision: Union[str, Sequence[str], None] = '176390fceeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_tenant_id'), 'agencies', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('primary_color', sa.String(length=7), nullable=True))
    op.add_column('tenants', sa.Column('secondary_color', sa.String(length=7), nullable=True))
    op.add_column('users', sa.Column('agency_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_agency_id'), 'users', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'users', 'agencies', ['agency_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_agency_id'), table_name='users')
    op.drop_column('users', 'agency_id')
    op.drop_column('tenants', 'secondary_color')
    op.drop_column('tenants', 'primary_color')
    op.drop_column('tenants', 'logo_url')
    op.drop_index(op.f('ix_agencies_tenant_id'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
