"""add_products_tables

Revision ID: efadc171562e
Revises: l2m3n4o5p6q7
Create Date: 2026-01-09 15:49:15.735232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efadc171562e'
down_revision: Union[str, Sequence[str], None] = 'l2m3n4o5p6q7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('price_ht', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('HEAT_PUMP', 'THERMOSTAT', 'OTHER', name='product_category'), nullable=False),
    sa.Column('module_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('product_compatibility',
    sa.Column('source_product_id', sa.Uuid(), nullable=False),
    sa.Column('target_product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_product_id', 'target_product_id')
    )
    op.create_table('product_heat_pumps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('etas_35', sa.Integer(), nullable=True),
    sa.Column('etas_55', sa.Integer(), nullable=True),
    sa.Column('power_minus_7', sa.Float(), nullable=True),
    sa.Column('power_minus_15', sa.Float(), nullable=True),
    sa.Column('power_supply', sa.Enum('MONOPHASE', 'TRIPHASE', name='power_supply_type'), nullable=True),
    sa.Column('refrigerant_type', sa.String(length=50), nullable=True),
    sa.Column('noise_level', sa.Float(), nullable=True),
    sa.Column('is_duo', sa.Boolean(), nullable=False),
    sa.Column('class_regulator', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_heat_pumps_product_id'), 'product_heat_pumps', ['product_id'], unique=True)
    op.create_table('product_thermostats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('class_rank', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_thermostats_product_id'), 'product_thermostats', ['product_id'], unique=True)
    op.drop_index(op.f('idx_base_temps_zone'), table_name='base_temperatures')
    op.create_index(op.f('ix_base_temperatures_zone'), 'base_temperatures', ['zone'], unique=False)
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_constraint(op.f('climate_zones_departement_key'), 'climate_zones', type_='unique')
    op.drop_index(op.f('idx_climate_zones_departement'), table_name='climate_zones')
    op.create_index(op.f('ix_climate_zones_departement'), 'climate_zones', ['departement'], unique=True)
    op.drop_index(op.f('idx_folders_client_id'), table_name='folders')
    op.drop_index(op.f('idx_folders_module_code'), table_name='folders')
    op.drop_index(op.f('idx_folders_property_id'), table_name='folders')
    op.drop_index(op.f('idx_folders_source_draft_id'), table_name='folders')
    op.drop_index(op.f('idx_folders_tenant_id'), table_name='folders')
    op.create_index(op.f('ix_folders_client_id'), 'folders', ['client_id'], unique=False)
    op.create_index(op.f('ix_folders_module_code'), 'folders', ['module_code'], unique=False)
    op.create_index(op.f('ix_folders_property_id'), 'folders', ['property_id'], unique=False)
    op.create_index(op.f('ix_folders_source_draft_id'), 'folders', ['source_draft_id'], unique=False)
    op.create_index(op.f('ix_folders_tenant_id'), 'folders', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_properties_is_active'), table_name='properties')
    op.drop_index(op.f('ix_properties_tenant_client'), table_name='properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_tenant_client'), 'properties', ['tenant_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_properties_is_active'), 'properties', ['is_active'], unique=False)
    op.drop_index(op.f('ix_folders_tenant_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_source_draft_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_property_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_module_code'), table_name='folders')
    op.drop_index(op.f('ix_folders_client_id'), table_name='folders')
    op.create_index(op.f('idx_folders_tenant_id'), 'folders', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_folders_source_draft_id'), 'folders', ['source_draft_id'], unique=False)
    op.create_index(op.f('idx_folders_property_id'), 'folders', ['property_id'], unique=False)
    op.create_index(op.f('idx_folders_module_code'), 'folders', ['module_code'], unique=False)
    op.create_index(op.f('idx_folders_client_id'), 'folders', ['client_id'], unique=False)
    op.drop_index(op.f('ix_climate_zones_departement'), table_name='climate_zones')
    op.create_index(op.f('idx_climate_zones_departement'), 'climate_zones', ['departement'], unique=False)
    op.create_unique_constraint(op.f('climate_zones_departement_key'), 'climate_zones', ['departement'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.drop_index(op.f('ix_base_temperatures_zone'), table_name='base_temperatures')
    op.create_index(op.f('idx_base_temps_zone'), 'base_temperatures', ['zone'], unique=False)
    op.drop_index(op.f('ix_product_thermostats_product_id'), table_name='product_thermostats')
    op.drop_table('product_thermostats')
    op.drop_index(op.f('ix_product_heat_pumps_product_id'), table_name='product_heat_pumps')
    op.drop_table('product_heat_pumps')
    op.drop_table('product_compatibility')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
